sonar.projectKey=tp1-cicd-app
sonar.projectName=TP1 CI/CD - Gym Tracker
sonar.projectVersion=1.0.0
sonar.sources=src,public
sonar.tests=src
sonar.test.inclusions=**/*.test.js
sonar.exclusions=**/*.test.js,node_modules/**,coverage/**,public/sw.js
sonar.coverage.exclusions=public/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
